FROM python:3.9-slim-buster

WORKDIR .

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY . .
CMD celery -A app.tasks worker --loglevel=info
